### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by TooLazyToComeUpWithUsername** [Athanaze/Blender-Normalize-Object#1]
Hello! I used your code in an exporter of mine but instead of looping through the mesh vertices I looped through the mesh bounding box values to compute the boundaries, like this:

```python
    selected_object = bpy.context.active_object

    min_bound = [selected_object.bound_box[0][0], selected_object.bound_box[0][1], selected_object.bound_box[0][2]]
    max_bound = [selected_object.bound_box[0][0], selected_object.bound_box[0][1], selected_object.bound_box[0][2]]
    
    for bound in selected_object.bound_box:
    
        min_bound[0] = min(min_bound[0], bound[0])
        min_bound[1] = min(min_bound[1], bound[1])
        min_bound[2] = min(min_bound[2], bound[2])
        
        max_bound[0] = max(max_bound[0], bound[0])
        max_bound[1] = max(max_bound[1], bound[1])
        max_bound[2] = max(max_bound[2], bound[2])
```
This should probably be faster in general (especially on big meshes with lots of triangles) since the documentation says that the bounding box always has 8 position vectors.
I verified the results and the resulting mesh perfectly fits inside a unit cube.

We could make it even faster by directly taking the two relevant vectors in the bounding box that would act as the minimum and maximum boundaries. The thing is, I do not know if bounding boxes store their vectors in the same order consistently so I do not know if this would be reliable.

I tested this on Blender 2.92.

**Comment by Athanaze** [comment]
That's cool !
Looks like your approach is a lot smarter than mine haha.
